# basic
title: Martin Beneš
description: This is where the description of your site will go.

# configuration
github_username: martinbenes1996
github_repo: "https://github.com/martinbenes1996/martinbenes1996.github.io.git"
permalink: pretty
baseurl: "/"

# contact
email: martinbenes1996@gmail.com
twitter_username: martinbenes1996

# insite settings
#remote_theme             : "mmistakes/minimal-mistakes@4.23.0"
# logic
paginate: 10
use_math: true
search_enabled: true
# theme
theme: jekyll-theme-minimal
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag

# analytics
google_analytics:

